---
- name: Install Docker on Debian 11
  hosts: all
  become: true

  tasks:
    - name: Install Docker dependencies
      command: "apt-get update && apt-get install -y curl gnupg lsb-release"

    - name: Add Docker GPG key
      command: "curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"

    - name: Add Docker repository
      command: "echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable' > /etc/apt/sources.list.d/docker.list"

    - name: Update apt cache
      command: "apt-get update"

    - name: Install Docker
      command: "apt-get install -y docker-ce docker-ce-cli containerd.io"

    - name: Start and enable Docker service
      command: "systemctl start docker && systemctl enable docker"
