---
- name: Install Docker on Debian 11
  hosts: all
  become: yes

  tasks:
    - name: Install Docker dependencies
      command:
        cmd: "apt-get update"
        warn: false

    - name: Install additional packages
      command:
        cmd: "apt-get install -y curl gnupg lsb-release"
        warn: false

    - name: Add Docker GPG key
      shell: "curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
      register: gpg_key_result
      failed_when: "'curl: option' in gpg_key_result.stderr"

    - name: Add Docker repository
      command:
        cmd: "echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable' > /etc/apt/sources.list.d/docker.list"
        warn: false

    - name: Update apt cache
      command:
        cmd: "apt-get update"
        warn: false

    - name: Install Docker
      command:
        cmd: "apt-get install -y docker-ce docker-ce-cli containerd.io"
        warn: false

    - name: Start and enable Docker service
      command:
        cmd: "systemctl start docker && systemctl enable docker"
        warn: false
